### ISSUE TITLE
Course Logo

### ISSUE THREAD

**Issue by NishitaJain** [kevinlin1/just-the-class#1]
Hey Kevin,

This template is awesome. I was wondering what the easiest way to add a logo to the title/navbar would be. Seems like the just-the-docs template has a config variable for `logo` that I don't see on this one. 

Thanks!

**Comment by kevinlin1** [comment]
Adding a `site.logo` field seems to work fine for me, though it's not included in the example `_config.yml`.

```
logo: "https://pmarsceill.github.io/just-the-docs/assets/images/just-the-docs.png"
```

You can replace the URL with your own relative path as shown in the [Configuration documentation](https://pmarsceill.github.io/just-the-docs/docs/configuration/#site-logo).
