### ISSUE TITLE
Dark Mode Toggle

### ISSUE THREAD

**Issue by Alireza1044** [kevinlin1/just-the-class#27]
Hi Kevin,

Nice job on this template. I just wanted to suggest a three-way dark mode toggle on the top right similar to what is implemented here:
https://peps.python.org

I know we can edit `_config.yml` to change the theme to dark, but it is before deployment and robs users of a choice. Could you please have a look into this?

Thanks!

**Comment by kevinlin1** [comment]
Hi @Alireza1044, this feature is currently being addressed upstream in just-the-docs/just-the-docs#1086. You can follow the progress there!
