### ISSUE TITLE
Site not displaying correctly

### ISSUE THREAD

**Issue by ykharitonova** [kevinlin1/just-the-class#3]
Hello, and thank you for providing this template.

I created a repository by following your link (1. Create [a new repository based on Just the Class](https://github.com/kevinlin1/just-the-class/generate).).

After pointing GitHub Pages to the master branch of my repo, the [resulting website](https://ucsb-ds.github.io/ds1-f20/) does not display correctly. When I inspect the site, I see the following errors:

```
just-the-docs.js:1 Failed to load resource: the server responded with a status of 404 ()
lunr.min.js:1 Failed to load resource: the server responded with a status of 404 ()
just-the-docs-default.css:1 Failed to load resource: the server responded with a status of 404 ()
just-the-docs.js:1 Failed to load resource: the server responded with a status of 404 ()
just-the-docs-default.css:1 Failed to load resource: the server responded with a status of 404 ()
```

Note that the site is displayed correctly, when I test it locally. I only see the following error on the console: `/sw.js' not found.`

Am I missing something in my repo setup?

**Comment by kevinlin1** [comment]
Hi @ykharitonova! You're right that the links are not correct. Make sure to update the [`_config.yml` file](https://github.com/ucsb-ds/ds1-f20/blob/5eeba619ca74a415bb25d664bb3befb17410689f/_config.yml#L16-L35) to reflect your course website hosting parameters. The `baseurl` should be `/ds1-f20` and the `url` should be `https://ucsb-ds.github.io`.

I'll update the getting started steps to reflect this and provide some additional examples. [CSE 390HA](https://gitlab.cs.washington.edu/cse390ha/20au/website) is a minimal example of a single-page website based on this template.

**Comment by ykharitonova** [comment]
@kevinlin1 Thank you! 

[Updating these two URLs](https://github.com/ucsb-ds/ds1-f20/commit/0859e4f170c78c20b54d7759dbb87e4bcb1d47d7) fixed the issue.
