### ISSUE TITLE
Staff photos stretched out

### ISSUE THREAD

**Issue by vitercik** [kevinlin1/just-the-class#30]
Hello, thanks for creating this awesome repo!

I'm having an issue where the staff photos appear very stretched out. This is also true (at least on my computer) at https://kevinl.info/just-the-class/staff/.

I've attached a screenshot.
![Screen Shot 2023-04-03 at 10 44 58 AM](https://user-images.githubusercontent.com/34546473/229587216-06b23cc0-9f16-4d24-883a-e8fd6a8bf2c8.png)

Do you have any idea what the issue may be? Thanks!

**Comment by kevinlin1** [comment]
Thanks, I forgot to backport a change from my current site. I just pushed commit a70b2c5, which should fix the problem.
