### ISSUE TITLE
Linking to other site pages 

### ISSUE THREAD

**Issue by ykharitonova** [kevinlin1/just-the-class#6]
I've been trying to figure out how to correctly link to different pages of the site. Specifically, I wanted the announcements to link to the corresponding pages elsewhere on the site.

Here's an undo of my previous attempt: the links in the announcement were resulting in 404, so I removed the text from the announcement and added it to the index page, where links worked correctly:
https://github.com/ucsb-ds/ds1-f20/commit/346c75d0cf47cce2cf7da7ea88a7ce2803039c10

Seems that I need to use `{{ site.baseurl }}` and drop `.md` in the page name.

The following links added to an announcement seem to work:
```
[Getting Started section]({{ site.baseurl }}/#getting-started)
or
[Getting Started section]({{ site.baseurl }}/index#getting-started)

Or to link to a calendar.md:
[Calendar]({{ site.baseurl }}/calendar).
```

Is this the correct/suggested way to link to the other pages of the site? 

If so, I was hoping that we can add it to the README.

Thank you!

**Comment by kevinlin1** [comment]
Good question. I recommend Jekyll's documentation on [Links](https://jekyllrb.com/docs/liquid/tags/#links): they use a special `link` tag that automatically determines the output path to a document, regardless of its filetype. Note that [GitHub Pages still uses Jekyll 3.x](https://pages.github.com/versions/), so we need to prepend `site.baseurl` to the examples in the documentation.

For anchor links to particular sections as in your "Getting Started section" example, I would add them after the `link` tag.

```
[Getting Started section]({{ site.baseurl }}{% link index.md %}#getting-started)
```

**Comment by ykharitonova** [comment]
@kevinlin1 Thank you! It worked well for both the links to pages as well as anchor links:
https://ucsb-ds.github.io/ds1-f20/announcements.
